import { jsPDF } from 'jspdf';

export interface PDFData {
    title: string;
    sections: {
        heading: string;
        content: string;
    }[];
}

export async function generateProjectPDF(data: PDFData): Promise<Buffer> {
    const doc = new jsPDF();
    let y = 20;
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const contentWidth = pageWidth - (margin * 2);

    // 1. Header Bar
    doc.setFillColor(31, 71, 136); // #1F4788 (Apple Blue-ish)
    doc.rect(0, 0, pageWidth, 40, 'F');

    // 2. Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(data.title.toUpperCase(), margin, 25);

    doc.setFontSize(10);
    doc.text('PM CHATT ASSISTANT | EXPERT PROJECT DOCUMENTATION', margin, 35);

    y = 60;

    // 3. Sections
    data.sections.forEach((section) => {
        // Check if we need a new page
        if (y > 270) {
            doc.addPage();
            y = 20;
        }

        // Heading
        doc.setTextColor(31, 71, 136);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(section.heading, margin, y);
        y += 10;

        // Body
        doc.setTextColor(60, 60, 60);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');

        const lines = doc.splitTextToSize(section.content, contentWidth);
        doc.text(lines, margin, y);
        y += (lines.length * 7) + 10;
    });

    // 4. Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount} | Generated by PM Chat Assistant`, pageWidth / 2, 285, { align: 'center' });
    }

    return Buffer.from(doc.output('arraybuffer'));
}
